collection:
  - name: This is a test name (test -1)
    description: This is a test description
  - name: This is another test name
    description: This is another test description
  - name: This is a test name (test -1)
    description: This is a test description
  - name: This is another test name
    description: This is another test description
  - name: This is a test name (test -1)
    description: This is a test description
  - name: This is another test name
    description: This is another test description
  - name: This is another test name
    description: This is another test description
